### ISSUE TITLE
[Bug] Missing files/games in gamewindow.pyw 

### ISSUE THREAD

**Issue by RehanChalana** [pinak22dhir/Python-Gamez-Arena#11]
![image](https://github.com/pinak22dhir/Python-Gamez-Arena/assets/139042983/9a33bd87-74bd-4bc8-9eaf-78fe74473680)

These files are running from local computer and not repository and hence either we should remove them or add these games

**Comment by pinak22dhir** [comment]
@RehanChalana waiting for another pr of yours regarding same, happy coding
