### ISSUE TITLE
[SWOC'24] Issue Templates

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [pinak22dhir/Python-Gamez-Arena#16]
Issue templates for your project like,

- Styling Request
- Documentation Request
- Bug Report
- New Features Request, etc.

This will help contributors and maintainers both to segregate which are related either styling, new features, bug, etc.

**Comment by Avdhesh-Varshney** [comment]
@pinak-dhir please assign this work to me to contribute in your repo under SWOC'24

**Comment by pinak22dhir** [comment]
happy coding @Avdhesh-Varshney
