### ISSUE TITLE
[SWOC'24] LICENCE for the project

### ISSUE THREAD

**Issue by Avdhesh-Varshney** [pinak22dhir/Python-Gamez-Arena#17]
I would like to request 
- the addition of a license 
- to enhance privacy protection and 
- address potential copyright infringement issues in the project.

**Comment by Avdhesh-Varshney** [comment]
@pinak-dhir please assign this task to me to contribute in your repo under SWOC'24

**Comment by pinak22dhir** [comment]
@Avdhesh-Varshney  i have created it , now you can do further changes

**Comment by Avdhesh-Varshney** [comment]
@pinak22dhir should i update the licence `2023-> 2024` ?
Also attach the Licence into contribution guidelines and in main readme file.

**Comment by pinak22dhir** [comment]
@Avdhesh-Varshney  don't include in main file but can change the year .

**Comment by VIDHISHAK15** [comment]
@Avdhesh-Varshney could you please assign me this issue

**Comment by Avdhesh-Varshney** [comment]
@VIDHISHAK15 This is already done by me. I don't know why this issue is not closed with pr.
