### ISSUE TITLE
Car game

### ISSUE THREAD

**Issue by VardaPanchal005** [pinak22dhir/Python-Gamez-Arena#3]
I want to make a car game where the speed of the car increases every few seconds and we have to dodge the obstacles with the help of Python.

Please assign this issue to me under SWOC @pinak22dhir

**Comment by pinak22dhir** [comment]
@VardaPanchal005  can you explain in detail?

**Comment by VardaPanchal005** [comment]
simple car game where it has to avoid other cars and the speed will increase every specified seconds. on the road.

**Comment by pinak22dhir** [comment]
nice idea, i assigned you this issue, now waiting for another pr of yours, good luck @VardaPanchal005 , happy coding

**Comment by VardaPanchal005** [comment]
Thank you

**Comment by pinak22dhir** [comment]
no progress @VardaPanchal005

**Comment by VardaPanchal005** [comment]
I made the game but I'm facing error in cloning repository

**Comment by VardaPanchal005** [comment]
<img width="753" alt="error" src="https://github.com/pinak22dhir/Python-Gamez-Arena/assets/114830938/8149b913-3d8f-4fd5-b30b-d76416419c49">

I tried some stackoverflow solutions but that didn't help either

**Comment by pinak22dhir** [comment]
try  to make another repository @VardaPanchal005

**Comment by VardaPanchal005** [comment]
are you suggesting that i try to clone in another repo ?
