### ISSUE TITLE
add games<flappy bird>

### ISSUE THREAD

**Issue by pinak22dhir** [pinak22dhir/Python-Gamez-Arena#41]
### Description

1. flappy bird

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/pinak22dhir/Python-Gamez-Arena/blob/main/contribution.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor

**Comment by praptisharma28** [comment]
I will love to add, you can assign me this @pinak22dhir . I will show you the result too before making a PR.

**Comment by TanushreeBorase** [comment]
I would like to work on this issue @pinak22dhir under swoc'24. Please assign me this issue.

**Comment by pinak22dhir** [comment]
@TanushreeBorase as @praptisharma28 ask first , so assigning it to her, you contribute in another issues or  make your own as hangman and egg catcher do not have any readme file  you can create issue for the same
