### ISSUE TITLE
make changes in space  invaders

### ISSUE THREAD

**Issue by pinak22dhir** [pinak22dhir/Python-Gamez-Arena#42]
### Description

Space Invaders" played a significant role in the popularization of video games and is considered a classic in the arcade gaming genre. Its simple yet addictive gameplay and iconic pixelated graphics have left a lasting impact on the gaming industry. 

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/pinak22dhir/Python-Gamez-Arena/blob/main/contribution.md)
- [ ] I am willing to work on this issue (optional)
- [ ] I am a SWOC'24 contributor

**Comment by praptisharma28** [comment]
Assign me @pinak22dhir under iwoc2024. Will do the change.
