### ISSUE TITLE
Add a tetris game

### ISSUE THREAD

**Issue by Kanavmh** [pinak22dhir/Python-Gamez-Arena#51]
### Description

A Tetris game using python and tkinter.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/pinak22dhir/Python-Gamez-Arena/blob/main/contribution.md)
- [X] I am willing to work on this issue (optional)
- [X] I am a SWOC'24 contributor

**Comment by Kanavmh** [comment]
do assign this to me @pinak22dhir

**Comment by Shashikumar-ezhilarasu** [comment]
I would love to work on this Tetris game using Python and Tkinter. Please assign this task to me @Kanavmh , and I will create a detailed README describing the game's functionality and setup too.

**Comment by pinak22dhir** [comment]
ok @Shashikumar-ezhilarasu

**Comment by Shashikumar-ezhilarasu** [comment]
Thanks for assigning the issue! I’ll start working on it and update here once I have progress @pinak22dhir

**Comment by Shashikumar-ezhilarasu** [comment]
Hi, I’ve worked on this Tetris game project and made improvements to the code. I’ve created a pull request (PR) for review. Could you please take a look at it and accept the changes if everything looks good? I’d appreciate any feedback or suggestions.

Thank you!! @pinak22dhir
