### ISSUE TITLE
enhance readme

### ISSUE THREAD

**Issue by pinak22dhir** [pinak22dhir/Python-Gamez-Arena#8]
you can enhance readme by detailing , or adding contributors

**Comment by rudransh61** [comment]
Can i do this

**Comment by pinak22dhir** [comment]
All the best,waiting for another pr on ur side ,happy coding @rudransh61

**Comment by rudransh61** [comment]
@pinak22dhir @pinak-dhir pls review the code

**Comment by rudransh61** [comment]
@pinak-dhir 
Pls review the new pr
